In [8]:
%sql select * from solix.AAA_DEPARTMENT_RELATION_1 limit 10;

Error:

In [7]:
%%sql
SELECT * FROM solix.aaa_department_relation_1 LIMIT 50

,dept_id,dept_code,dept_name,location,manager_name,budget_amount,created_date,last_update_date
0,1,21,dep,hyd,ss,100.0,NaT,NaT
1,50,70,Department_50,Location_10,Manager_50,50000.0,2026-06-07 02:27:56.380406,2026-06-07 04:27:56.380406
2,51,71,Department_51,Location_1,Manager_51,51000.0,2026-06-08 02:27:56.380406,2026-06-08 04:27:56.380406
3,52,72,Department_52,Location_2,Manager_52,52000.0,2026-06-09 02:27:56.380406,2026-06-09 04:27:56.380406
4,53,73,Department_53,Location_3,Manager_53,53000.0,2026-06-10 02:27:56.380406,2026-06-10 04:27:56.380406
5,54,74,Department_54,Location_4,Manager_54,54000.0,2026-06-11 02:27:56.380406,2026-06-11 04:27:56.380406
6,55,75,Department_55,Location_5,Manager_55,55000.0,2026-06-12 02:27:56.380406,2026-06-12 04:27:56.380406
7,56,76,Department_56,Location_6,Manager_56,56000.0,2026-06-13 02:27:56.380406,2026-06-13 04:27:56.380406
8,57,77,Department_57,Location_7,Manager_57,57000.0,2026-06-14 02:27:56.380406,2026-06-14 04:27:56.380406
9,58,78,Department_58,Location_8,Manager_58,58000.0,2026-06-15 02:27:56.380406,2026-06-15 04:27:56.380406
10,59,79,Department_59,Location_9,Manager_59,59000.0,2026-06-16 02:27:56.380406,2026-06-16 04:27:56.380406
11,60,80,Department_60,Location_10,Manager_60,60000.0,2026-06-17 02:27:56.380406,2026-06-17 04:27:56.380406
12,61,81,Department_61,Location_1,Manager_61,61000.0,2026-06-18 02:27:56.380406,2026-06-18 04:27:56.380406
13,62,82,Department_62,Location_2,Manager_62,62000.0,2026-06-19 02:27:56.380406,2026-06-19 04:27:56.380406
14,63,83,Department_63,Location_3,Manager_63,63000.0,2026-06-20 02:27:56.380406,2026-06-20 04:27:56.380406
15,64,84,Department_64,Location_4,Manager_64,64000.0,2026-06-21 02:27:56.380406,2026-06-21 04:27:56.380406
16,65,85,Department_65,Location_5,Manager_65,65000.0,2026-06-22 02:27:56.380406,2026-06-22 04:27:56.380406
17,66,86,Department_66,Location_6,Manager_66,66000.0,2026-06-23 02:27:56.380406,2026-06-23 04:27:56.380406
18,67,87,Department_67,Location_7,Manager_67,67000.0,2026-06-24 02:27:56.380406,2026-06-24 04:27:56.380406
19,68,88,Department_68,Location_8,Manager_68,68000.0,2026-06-25 02:27:56.380406,2026-06-25 04:27:56.380406
20,69,89,Department_69,Location_9,Manager_69,69000.0,2026-06-26 02:27:56.380406,2026-06-26 04:27:56.380406
21,70,90,Department_70,Location_10,Manager_70,70000.0,2026-06-27 02:27:56.380406,2026-06-27 04:27:56.380406
22,71,91,Department_71,Location_1,Manager_71,71000.0,2026-06-28 02:27:56.380406,2026-06-28 04:27:56.380406
23,72,92,Department_72,Location_2,Manager_72,72000.0,2026-06-29 02:27:56.380406,2026-06-29 04:27:56.380406
24,73,93,Department_73,Location_3,Manager_73,73000.0,2026-06-30 02:27:56.380406,2026-06-30 04:27:56.380406
25,74,94,Department_74,Location_4,Manager_74,74000.0,2026-07-01 02:27:56.380406,2026-07-01 04:27:56.380406
26,75,95,Department_75,Location_5,Manager_75,75000.0,2026-07-02 02:27:56.380406,2026-07-02 04:27:56.380406
27,76,96,Department_76,Location_6,Manager_76,76000.0,2026-07-03 02:27:56.380406,2026-07-03 04:27:56.380406
28,77,97,Department_77,Location_7,Manager_77,77000.0,2026-07-04 02:27:56.380406,2026-07-04 04:27:56.380406
29,78,98,Department_78,Location_8,Manager_78,78000.0,2026-07-05 02:27:56.380406,2026-07-05 04:27:56.380406
30,79,99,Department_79,Location_9,Manager_79,79000.0,2026-07-06 02:27:56.380406,2026-07-06 04:27:56.380406
31,80,100,Department_80,Location_10,Manager_80,80000.0,2026-07-07 02:27:56.380406,2026-07-07 04:27:56.380406
32,81,101,Department_81,Location_1,Manager_81,81000.0,2026-07-08 02:27:56.380406,2026-07-08 04:27:56.380406
33,82,102,Department_82,Location_2,Manager_82,82000.0,2026-07-09 02:27:56.380406,2026-07-09 04:27:56.380406
34,83,103,Department_83,Location_3,Manager_83,83000.0,2026-07-10 02:27:56.380406,2026-07-10 04:27:56.380406
35,84,104,Department_84,Location_4,Manager_84,84000.0,2026-07-11 02:27:56.380406,2026-07-11 04:27:56.380406
36,85,105,Department_85,Location_5,Manager_85,85000.0,2026-07-12 02:27:56.380406,2026-07-12 04:27:56.380406
37,86,106,Department_86,Location_6,Manager_86,86000.0,2026-07-13 02:27:56.380406,2026-07-13 04:27:56.380406
38,87,107,Department_87,Location_7,Manager_87,87000.0,2026-07-14 02:27:56.380406,2026-07-14 04:27:56.380406
39,88,108,Department_88,Location_8,Manager_88,88000.0,2026-07-15 02:27:56.380406,2026-07-15 04:27:56.380406
40,89,109,Department_89,Location_9,Manager_89,89000.0,2026-07-16 02:27:56.380406,2026-07-16 04:27:56.380406
41,90,110,Department_90,Location_10,Manager_90,90000.0,2026-07-17 02:27:56.380406,2026-07-17 04:27:56.380406
42,91,111,Department_91,Location_1,Manager_91,91000.0,2026-07-18 02:27:56.380406,2026-07-18 04:27:56.380406
43,92,112,Department_92,Location_2,Manager_92,92000.0,2026-07-19 02:27:56.380406,2026-07-19 04:27:56.380406
44,93,113,Department_93,Location_3,Manager_93,93000.0,2026-07-20 02:27:56.380406,2026-07-20 04:27:56.380406
45,94,114,Department_94,Location_4,Manager_94,94000.0,2026-07-21 02:27:56.380406,2026-07-21 04:27:56.380406
46,95,115,Department_95,Location_5,Manager_95,95000.0,2026-07-22 02:27:56.380406,2026-07-22 04:27:56.380406
47,96,116,Department_96,Location_6,Manager_96,96000.0,2026-07-23 02:27:56.380406,2026-07-23 04:27:56.380406
48,97,117,Department_97,Location_7,Manager_97,97000.0,2026-07-24 02:27:56.380406,2026-07-24 04:27:56.380406
49,98,118,Department_98,Location_8,Manager_98,98000.0,2026-07-25 02:27:56.380406,2026-07-25 04:27:56.380406

In [13]:
%%sql
SELECT * FROM solix.aaa_department_relation_1 LIMIT 50

,dept_id,dept_code,dept_name,location,manager_name,budget_amount,created_date,last_update_date
0,1,21,dep,hyd,ss,100.0,NaT,NaT
1,50,70,Department_50,Location_10,Manager_50,50000.0,2026-06-07 02:27:56.380406,2026-06-07 04:27:56.380406
2,51,71,Department_51,Location_1,Manager_51,51000.0,2026-06-08 02:27:56.380406,2026-06-08 04:27:56.380406
3,52,72,Department_52,Location_2,Manager_52,52000.0,2026-06-09 02:27:56.380406,2026-06-09 04:27:56.380406
4,53,73,Department_53,Location_3,Manager_53,53000.0,2026-06-10 02:27:56.380406,2026-06-10 04:27:56.380406
5,54,74,Department_54,Location_4,Manager_54,54000.0,2026-06-11 02:27:56.380406,2026-06-11 04:27:56.380406
6,55,75,Department_55,Location_5,Manager_55,55000.0,2026-06-12 02:27:56.380406,2026-06-12 04:27:56.380406
7,56,76,Department_56,Location_6,Manager_56,56000.0,2026-06-13 02:27:56.380406,2026-06-13 04:27:56.380406
8,57,77,Department_57,Location_7,Manager_57,57000.0,2026-06-14 02:27:56.380406,2026-06-14 04:27:56.380406
9,58,78,Department_58,Location_8,Manager_58,58000.0,2026-06-15 02:27:56.380406,2026-06-15 04:27:56.380406
10,59,79,Department_59,Location_9,Manager_59,59000.0,2026-06-16 02:27:56.380406,2026-06-16 04:27:56.380406
11,60,80,Department_60,Location_10,Manager_60,60000.0,2026-06-17 02:27:56.380406,2026-06-17 04:27:56.380406
12,61,81,Department_61,Location_1,Manager_61,61000.0,2026-06-18 02:27:56.380406,2026-06-18 04:27:56.380406
13,62,82,Department_62,Location_2,Manager_62,62000.0,2026-06-19 02:27:56.380406,2026-06-19 04:27:56.380406
14,63,83,Department_63,Location_3,Manager_63,63000.0,2026-06-20 02:27:56.380406,2026-06-20 04:27:56.380406
15,64,84,Department_64,Location_4,Manager_64,64000.0,2026-06-21 02:27:56.380406,2026-06-21 04:27:56.380406
16,65,85,Department_65,Location_5,Manager_65,65000.0,2026-06-22 02:27:56.380406,2026-06-22 04:27:56.380406
17,66,86,Department_66,Location_6,Manager_66,66000.0,2026-06-23 02:27:56.380406,2026-06-23 04:27:56.380406
18,67,87,Department_67,Location_7,Manager_67,67000.0,2026-06-24 02:27:56.380406,2026-06-24 04:27:56.380406
19,68,88,Department_68,Location_8,Manager_68,68000.0,2026-06-25 02:27:56.380406,2026-06-25 04:27:56.380406
20,69,89,Department_69,Location_9,Manager_69,69000.0,2026-06-26 02:27:56.380406,2026-06-26 04:27:56.380406
21,70,90,Department_70,Location_10,Manager_70,70000.0,2026-06-27 02:27:56.380406,2026-06-27 04:27:56.380406
22,71,91,Department_71,Location_1,Manager_71,71000.0,2026-06-28 02:27:56.380406,2026-06-28 04:27:56.380406
23,72,92,Department_72,Location_2,Manager_72,72000.0,2026-06-29 02:27:56.380406,2026-06-29 04:27:56.380406
24,73,93,Department_73,Location_3,Manager_73,73000.0,2026-06-30 02:27:56.380406,2026-06-30 04:27:56.380406
25,74,94,Department_74,Location_4,Manager_74,74000.0,2026-07-01 02:27:56.380406,2026-07-01 04:27:56.380406
26,75,95,Department_75,Location_5,Manager_75,75000.0,2026-07-02 02:27:56.380406,2026-07-02 04:27:56.380406
27,76,96,Department_76,Location_6,Manager_76,76000.0,2026-07-03 02:27:56.380406,2026-07-03 04:27:56.380406
28,77,97,Department_77,Location_7,Manager_77,77000.0,2026-07-04 02:27:56.380406,2026-07-04 04:27:56.380406
29,78,98,Department_78,Location_8,Manager_78,78000.0,2026-07-05 02:27:56.380406,2026-07-05 04:27:56.380406
30,79,99,Department_79,Location_9,Manager_79,79000.0,2026-07-06 02:27:56.380406,2026-07-06 04:27:56.380406
31,80,100,Department_80,Location_10,Manager_80,80000.0,2026-07-07 02:27:56.380406,2026-07-07 04:27:56.380406
32,81,101,Department_81,Location_1,Manager_81,81000.0,2026-07-08 02:27:56.380406,2026-07-08 04:27:56.380406
33,82,102,Department_82,Location_2,Manager_82,82000.0,2026-07-09 02:27:56.380406,2026-07-09 04:27:56.380406
34,83,103,Department_83,Location_3,Manager_83,83000.0,2026-07-10 02:27:56.380406,2026-07-10 04:27:56.380406
35,84,104,Department_84,Location_4,Manager_84,84000.0,2026-07-11 02:27:56.380406,2026-07-11 04:27:56.380406
36,85,105,Department_85,Location_5,Manager_85,85000.0,2026-07-12 02:27:56.380406,2026-07-12 04:27:56.380406
37,86,106,Department_86,Location_6,Manager_86,86000.0,2026-07-13 02:27:56.380406,2026-07-13 04:27:56.380406
38,87,107,Department_87,Location_7,Manager_87,87000.0,2026-07-14 02:27:56.380406,2026-07-14 04:27:56.380406
39,88,108,Department_88,Location_8,Manager_88,88000.0,2026-07-15 02:27:56.380406,2026-07-15 04:27:56.380406
40,89,109,Department_89,Location_9,Manager_89,89000.0,2026-07-16 02:27:56.380406,2026-07-16 04:27:56.380406
41,90,110,Department_90,Location_10,Manager_90,90000.0,2026-07-17 02:27:56.380406,2026-07-17 04:27:56.380406
42,91,111,Department_91,Location_1,Manager_91,91000.0,2026-07-18 02:27:56.380406,2026-07-18 04:27:56.380406
43,92,112,Department_92,Location_2,Manager_92,92000.0,2026-07-19 02:27:56.380406,2026-07-19 04:27:56.380406
44,93,113,Department_93,Location_3,Manager_93,93000.0,2026-07-20 02:27:56.380406,2026-07-20 04:27:56.380406
45,94,114,Department_94,Location_4,Manager_94,94000.0,2026-07-21 02:27:56.380406,2026-07-21 04:27:56.380406
46,95,115,Department_95,Location_5,Manager_95,95000.0,2026-07-22 02:27:56.380406,2026-07-22 04:27:56.380406
47,96,116,Department_96,Location_6,Manager_96,96000.0,2026-07-23 02:27:56.380406,2026-07-23 04:27:56.380406
48,97,117,Department_97,Location_7,Manager_97,97000.0,2026-07-24 02:27:56.380406,2026-07-24 04:27:56.380406
49,98,118,Department_98,Location_8,Manager_98,98000.0,2026-07-25 02:27:56.380406,2026-07-25 04:27:56.380406